### ISSUE TITLE
In demo; Dead links to plugins

### ISSUE THREAD

**Issue by twMat** [Spangenhelm/TW5-EnhancedSearchResults#5]
Hey guys! It should come as no surprise that I'm really happy to see you're progressing with this!

I intend to install this for TWaddle. Figure this is good not only because, well, this plugin is better than default search, but also because it's a site I "promote" every now and then.

However, on http://spangenhelm.github.io/TW5-EnhancedSearchResults/

...the download links are dead.

Also, those links stat 5.1.7 and 5.1.8 but not 5.1.9.

**Comment by felixhayashi** [comment]
Again many thanks @twMat for supporting this :+1: 

> ...the download links are dead.

Whooooops. I'll fix that or if @Spangenhelm finds the time to do so it would be great!

I'll ping back once it is done.

-Felix

**Comment by Spangenhelm** [comment]
Done! I have fixed the links and also added your name as "author" and as part of the plugin itself in the demo, so make sure your future modifications matches those changes ;-)

+

Ps: thank you for your support @twMat :+1:

**Comment by twMat** [comment]
Excellente! Now installed on the admin version of TWaddle for try out :+1: 

Detail; The text states

 "When running TiddlyWiki in stand-alone mode, grab one of the versions below and make sure you pick the version that matches your TiddlyWiki version." 
...

**Comment by Spangenhelm** [comment]
Done! I have shortened the text since there is only one version left and updated the version number..
Thanks a lot for your feedback and your enthousiasm!

**Comment by felixhayashi** [comment]
@twMat 

By the way, your TWaddle site is great. It is nice to see somebody actively focussing on the big picture around TiddlyWiki (e.g. infrastructure, marketing, world domination etc.).

-Felix

**Comment by twMat** [comment]
@Spangenhelm - great!

@felixhayashi - Thanx Felix! In my view, to _really_ make TW improve that's where the focus should be. But my incompetence in implementing the ideas makes me feel like I'm in a prison :-/
