### ISSUE TITLE
Include a short css flash to indicate the opening of the search tab

### ISSUE THREAD

**Issue by felixhayashi** [Spangenhelm/TW5-EnhancedSearchResults#7]
To make it more explicit that the search tab has been opened, make the tab background green (or other color) and fade back to a normal color in a span of e.g. 3 seconds.

This idea came up here:

https://github.com/Jermolene/TiddlyWiki5/issues/1066#issuecomment-143665020

**Comment by Spangenhelm** [comment]
Hi Felix, are we really going to add **flashing colors** to tw ?! I must have jumped back to the web from the nineties where websites looked like christmas trees... please, i beg you, don't go that way !

**Comment by felixhayashi** [comment]
Hi @Spangenhelm

Haha you mean like this: http://www.angelfire.com/super/badwebs/

Ok, no problem. I'll close this issue then. I just thought it's worth creating an issue for as it was mentioned in the big discussion about the TW search. But I am also not in favour of it :)

-Felix

**Comment by Spangenhelm** [comment]
Oh! i prefer that lol ;-)
